### ISSUE TITLE
May I know how to generate proposals on my own datasets?

### ISSUE THREAD

**Issue by Ayatans** [jinhseo/OD-WSCL#1]
I found that the proposals of VOC and COCO are directly given in the Dropbox, what if I want to apply the method on my own datasets? Could you please show me the link of the codes you used to generate proposals, like SS and MCG? Thanks a lot!

**Comment by jinhseo** [comment]
I used the pre-defined proposals for both of SS and MCG.

You can refer to [this link](https://github.com/jponttuset/mcg) to generate proposals using MCG algorithm on your own dataset.

**Comment by Ayatans** [comment]
Thanks, I will try it.
