### ISSUE TITLE
The function of similarity network

### ISSUE THREAD

**Issue by CatOneTwo** [jinhseo/OD-WSCL#10]
Dear author, thanks for your excellent work. 

I wonder whether the FC layer in the similar head is necessary and what other functions it has besides dimensionality reduction. Besides, is it possible to perform contrastive learning directly on the original roi feature? Thank you~

**Comment by jinhseo** [comment]
Hi, thank you for your interesting question.
Basically, I would say that it is not 'necessary' to run object discovery.
But motivated by contrastive learning, I apply similarity head to place low-dimension feature space which can help to understand similarity in embedding space.
So you can use roi features(4096) to measure similarity, but some details (activation function in similarity head and the output after dropout) probably brings different result.
