### ISSUE TITLE
Which are the right proposals to coco dataset?

### ISSUE THREAD

**Issue by luiszeni** [jinhseo/OD-WSCL#11]
Hi, in the config file to train the model in the COCO dataset the file name of the proposals are these:

 TRAIN: ('proposal/MCG/coco/MCG-coco_2014_train-boxes.pkl',)
 TEST:  ('proposal/MCG/coco/MCG-coco_2014_val-boxes.pkl',)
  
However, in the dropbox that you provided with the proposals (https://www.dropbox.com/sh/sprm4dxg7l22jrg/AAD6L6JUOSxrBp8x3zG8D4F0a/MCG/coco?dl=0&subfolder_nav_tracking=1) the names are these:
  
MCG-coco14_minival.pkl
MCG-coco14_test-dev.pkl
MCG-coco14_train.pkl
MCG-coco14_val.pkl

Are these the correct proposas?  I tried to train the model using them, changing their names in the cfg file,  but the results where a lot lower than the reported in the paper. 

Any tip here ?

**Comment by jinhseo** [comment]
First of all, sorry for the incorrect configs in the repo. I just uploaded correct one.

The iteration steps should be 130k for COCO following the details in the paper.

For my environment at that time, the single gpu with large memory A100 48GB brings the best result.

**Comment by luiszeni** [comment]
ty
