### ISSUE TITLE
error: command '/usr/bin/g++' failed with exit code 1

### ISSUE THREAD

**Issue by ZiMo-Chen** [jinhseo/OD-WSCL#2]
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cpu/nms_cpu.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/ROIAlign_cuda.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/ROIPool_cuda.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/SigmoidFocalLoss_cuda.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/deform_conv_cuda.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/deform_conv_kernel_cuda.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/deform_pool_cuda.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/deform_pool_kernel_cuda.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/cuda/nms.o: No such file or directory
g++: error: /home/cxq/dp_work/objdetection/OD-WSCL/build/temp.linux-x86_64-cpython-37/home/cxq/dp_work/objdetection/OD-WSCL/wetectron/csrc/vision.o: No such file or directory

Hello, the above error occurs when I execute this line of code
python setup.py develop

**Comment by jinhseo** [comment]
Hi, I reckon you didn't install apex in a proper way.
Also you need to run build command: 'python setup.py build develop'
