### ISSUE TITLE
about Object Discovery

### ISSUE THREAD

**Issue by ZiMo-Chen** [jinhseo/OD-WSCL#4]
Hello, excuse me, where does your code reflect the "Object Discovery" in the paper?

**Comment by jinhseo** [comment]
You can find for code implementation of object discovery module only at https://github.com/jinhseo/OD-WSCL/blob/fd1e646d87ae5732b1b3b2226b09a31b1c01dfd2/wetectron/modeling/roi_heads/weak_head/pseudo_label_generator.py#L135
