### ISSUE TITLE
error：cannot import name 'Attention_DropBlock'

### ISSUE THREAD

**Issue by Liuyin159** [jinhseo/OD-WSCL#5]
ImportError: cannot import name 'Attention_DropBlock' from 'wetectron.modeling.dropblock.drop_block' (/home/liuyin/WSOD/OD-WSCL/wetectron/modeling/dropblock/drop_block.py)ImportError.

I found that there is no implementation of Attention_DropBlock in the code?

**Comment by BugOOM** [comment]
> ImportError: cannot import name 'Attention_DropBlock' from 'wetectron.modeling.dropblock.drop_block' (/home/liuyin/WSOD/OD-WSCL/wetectron/modeling/dropblock/drop_block.py)ImportError.
> 
> I found that there is no implementation of Attention_DropBlock in the code?

同样的问题。。。作者这部分代码是不是不想放

**Comment by jinhseo** [comment]
Sorry for the inconvenience, the code implementation of Attention_DropBlock is not completed.
I updated some code simply commenting it out.
