### ISSUE TITLE
steps to take for own dataset

### ISSUE THREAD

**Issue by broesmelii** [jinhseo/OD-WSCL#8]
Hi jinhseo,
Thank you for the code. I am currently trying to implement your model on a dataset of mine which has images with image labels. Your model seems perfect for it. However it is my first such project and while I have tried to get the model running on my dataset for the last weeks, I could need some help. Your feedback would be highly appreciated!!

Things I have already done:
- installed the model - it runs for the provided datasets
- constructed coco-annotations that provide bboxes of [1,1,1,1] (i heard this is the correct way to do image level annotation)
- put my images in the OD-WSCL/dataset/coco folder
- provided annotations in the OD-WSCL/dataset/coco/annotation folder (myds_val.json, myds_train.json)
- downloaded the proposals
- adapted the ODWSCL/wetectron/config/paths_catalogue.py file to include my datasets
- adapted the config file and used the coco proposal files:

`
DB:
  METHOD: 'dropblock'
DATASETS:
  TRAIN: ("cmydf_train",)
PROPOSAL_FILES:
  TRAIN: ('proposal/MCG/coco/MCG-coco_2014_train-boxes.pkl',)
`
unfortunately i get the error that my dataset is not available, when trying to run the model.

Could you give me feedback on my steps? Is there something missing? 

Thank you for your time!
Ben

**Comment by jinhseo** [comment]
Thank you for your words.
Before providing further responses, it's important to note that if you want to apply custom dataset, you will need images and corresponding image labels, and candidate bbox specific to the target dataset.
Therefore, it is desirable to configure a custom dataloader as you tried, and in the config - proposal section, you should specify the candidate bbox extract from SS/MCG algorithm. Additionally, based on the information provided, it seems that the error message is related to an import issue in the code, although I cannot be certain just by looking at it.
